# Generated by Django 3.1.3 on 2021-06-21 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', django_cpf_cnpj.fields.CPFField(max_length=14, unique=True)),
                ('nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=12)),
                ('endereco', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=4)),
                ('complemento', models.CharField(max_length=150)),
                ('bairro', models.CharField(max_length=30)),
                ('CEP', models.CharField(max_length=8)),
                ('sexo', models.CharField(choices=[['Feminino', 'Feminino'], ['Masculino', 'Masculino']], max_length=50)),
                ('grupo', models.CharField(choices=[['Profissional de saúde', 'Profissional de saúde'], ['Trabalhador em saúde sem conselho de classe', 'Trabalhador em saúde sem conselho de classe'], ['Doula', 'Doula'], ['Cuidador', 'Cuidador'], ['Acamado com 60 anos ou mais', 'Acamado com 60 anos ou mais'], ['Pessoa com 80 anos ou mais', 'Pessoa com 80 anos ou mais'], ['Pessoa entre 75 e 79 anos', 'Pessoa entre 75 e 79 anos'], ['Pessoa entre 70 e 74 anos', 'Pessoa entre 70 e 74 anos'], ['Pessoa entre 65 e 69 anos', 'Pessoa entre 65 e 69 anos'], ['Pessoa entre 60 e 64 anos', 'Pessoa entre 60 e 64 anos'], ['População Geral de 45 a 59 anos', 'População Geral de 45 a 59 anos'], ['Policial Militar', 'Policial Militar'], ['Policial Civil', 'Policial Civil'], ['Policial Federal', 'Policial Federal'], ['Agente da Receita Federal', 'Agente da Receita Federal'], ['Policial Rodoviário', 'Policial Rodoviário'], ['Agente Penitenciário / Policial Penal', 'Agente Penitenciário / Policial Penal'], ['Trabalhadores de Unidades Socioeducativas', 'Trabalhadores de Unidades Socioeducativas'], ['Trabalhador do Sistema Prisional', 'Trabalhador do Sistema Prisional'], ['Bombeiro Civil', 'Bombeiro Civil'], ['Bombeiro Militar', 'Bombeiro Militar'], ['Guarda Municipal', 'Guarda Municipal'], ['Membro do Exército', 'Membro do Exército'], ['Membro da Marinha', 'Membro da Marinha'], ['Membro da Aeronáutica', 'Membro da Aeronáutica'], ['Trabalhador de Transporte Aéreo', 'Trabalhador de Transporte Aéreo'], ['Professor', 'Professor'], ['Trabalhador da Educação', 'Trabalhador da Educação'], ['Assistente Social', 'Assistente Social'], ['Trabalhador da Assistência Social', 'Trabalhador da Assistência Social'], ['População Privada de Liberdade', 'População Privada de Liberdade']], max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
